module.exports.newsValidation = require('./news.validation')
module.exports.tourValidation = require('./tour.validation')
module.exports.authValidation = require('./auth.validation')
module.exports.ticketValidation = require('./ticket.validation')
module.exports.feedbackValidation = require('./feedback.validation')
module.exports.userValidation = require('./user.validation')