module.exports.tourService = require('./tour.service')
module.exports.userService = require('./user.service')
module.exports.ticketService = require('./ticket.service')
module.exports.newsService = require('./news.service')
module.exports.authService = require('./auth.service')
module.exports.feedbackService = require('./feedback.service')
